### ISSUE TITLE
Outlook Listings Have numbers double

### ISSUE THREAD

**Issue by MichaelPeter** [nickrussler/email-to-pdf-converter#35]
Hi Nick, 

really cool converter it is quite nice how it renders even nice things!
I am evaluating it right now and see what is not yet working and forked for potential fixes.

I created a test msg file with Outlook 2019 and there listed item:
remove the txt at the end.
[test mail with picture.msg.txt](https://github.com/nickrussler/email-to-pdf-converter/files/6561184/test.mail.with.picture.msg.txt)

Left the mail in Outlook 2019 right as Pdf

![grafik](https://user-images.githubusercontent.com/4217002/119992866-43b2f500-bfcb-11eb-9f9d-3b94a3c121c9.png)

as you see the listings are double

**Comment by nickrussler** [comment]
Internally I use 

implementation 'org.simplejavamail:simple-java-mail:8.11.1'
implementation 'org.simplejavamail:outlook-module:8.11.1'

to convert from msg to eml. 

I dumped the converted eml, opened it in outlook and could observe the same error. So the problem lies with the conversion.

[text.eml.txt](https://github.com/user-attachments/files/15519415/text.eml.txt)

**Comment by nickrussler** [comment]
I opened an issue with the conversion library: https://github.com/bbottema/simple-java-mail/issues/530

**Comment by bbottema** [comment]
Issue has been addressed in 8.11.2. Thanks for your assistance!

**Comment by nickrussler** [comment]
@MichaelPeter issue should be fixed with the latest commit. Please confirm with 

https://github.com/nickrussler/email-to-pdf-converter/actions/runs/9435991451/artifacts/1582956775
