### ISSUE TITLE
Incoming Apple-Mail: e-mail-body is not displayed in the pdf

### ISSUE THREAD

**Issue by mrchang0815** [nickrussler/email-to-pdf-converter#70]
If I receive an e-mail composed by "Apple-Mail", the headers and attachments are fine in the pdf but the message body is not displayed in the pdf.

I attached a sample EML file as .txt file (`debug.eml.txt`): Yes. Anonymized, cropped pdf-attachment.

[debug.eml.txt](https://github.com/user-attachments/files/15612522/debug.eml.txt)

**Comment by nickrussler** [comment]
This due to an unusual structure:
```
-----------Mime Message-----------
> multipart/alternative
> |  text/plain
> |  multipart/mixed
> |  |  text/html
> |  |  application/pdf; inline
> |  |  text/html
----------------------------------
```

For multipart/alternative there is clear guidance "In general, choosing the best type means displaying only the LAST part that can be displayed.". For "multipart/mixed" "the body parts are independent" (https://datatracker.ietf.org/doc/html/rfc2046). So the correct implementation would be to select **both** text/html. I will instead add a heuristic to select the larger one.

See also https://stackoverflow.com/questions/26254809/multiple-content-type-text-html-inside-a-multipart-mixed

**Comment by nickrussler** [comment]
Should be fixed in https://github.com/nickrussler/email-to-pdf-converter/releases/tag/3.0.0

Please confirm if this works now.

**Comment by mrchang0815** [comment]
Good morning,

perfect, everything works now as expected. Thank you!

Regards,
mrchang0815
